export enum QueryKeys {
  // user related
  GET_USER = "GET_USER",
  GET_USER_BY_ID = "GET_USER_BY_ID",
  GET_USERS = "GET_USERS",
  LOGIN_USER = "LOGIN_USER",
  REGISTER_USER = "REGISTER_USER",
  UPDATE_USER = "UPDATE_USER",
}
