export enum QueryKeys {
  // user related
  GET_USER = "GET_USER",
  GET_USER_BY_ID = "GET_USER_BY_ID",
  GET_USERS = "GET_USERS",
  LOGIN_USER = "LOGIN_USER",
  REGISTER_USER = "REGISTER_USER",
  UPDATE_USER = "UPDATE_USER",

  // game related
  CREATE_GAME = "CREATE_GAME",
  UPDATE_GAME = "UPDATE_GAME",
  GET_GAMES_PLAYED_COUNT = "GET_GAMES_PLAYED_COUNT",

  // movie related
  CREATE_MOVIE = "CREATE_MOVIE",
}
